services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    networks:
      - app-network
    command: >
      sh -c "
        echo 'Waiting for postgres...' &&
        sleep 5 &&
        alembic upgrade head &&
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5


  worker:
    build: .
    command: celery -A app.celery_app.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - postgres
      - app
      - redis
    networks:
      - app-network

  flower:
    build: .
    command: celery -A app.celery_app.celery_app flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - worker
    networks:
      - app-network


  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: xpress-ai
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
  postgres_data:

networks:
  app-network:
    driver: bridge 