"""Add user table

Revision ID: 9e868ca8e6dd
Revises: 
Create Date: 2025-04-25 15:41:59.728884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e868ca8e6dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=True),
    sa.Column('x_user_id', sa.BigInteger(), nullable=True),
    sa.Column('x_screen_name', sa.String(length=255), nullable=True),
    sa.Column('ai_role_id', sa.Integer(), nullable=True),
    sa.Column('credit', sa.Integer(), nullable=False),
    sa.Column('total_generated', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    sa.UniqueConstraint('wallet_address'),
    sa.UniqueConstraint('x_screen_name'),
    sa.UniqueConstraint('x_user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
