"""update model

Revision ID: bed154467858
Revises: b153db2db533
Create Date: 2025-05-20 17:29:43.046584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bed154467858'
down_revision: Union[str, None] = 'b153db2db533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweet_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('x_user_id', sa.String(length=255), nullable=False),
    sa.Column('x_screen_name', sa.String(length=255), nullable=False),
    sa.Column('tweet_history', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweet_history')
    # ### end Alembic commands ###
